export const UPDATE_ENTITIES = 'UPDATE_ENTITIES';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';
export const SET_CURRENT_GUILD = 'SET_CURRENT_GUILD';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOG_OUT = 'LOG_OUT'
